name: Docker CI

on: 
  push: 
    branches: [ main ]
  
jobs: 
  build: 
    timeout-minutes: 10 
    
    runs-on: ubuntu-latest 
    
    steps:
      - name: set up
        run: docker compose up




