name: Docker CI

on: 
  push: 
    branches: [ feature-1 ]
  
jobs: 
  build: 
    timeout-minutes: 20 
    runs-on: ubuntu-latest  # docker is preloaded in this vm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Local Images 
        id: local-images 
        uses: actions/cache@v3 
        with: 
          path: /var/lib/docker/ 
          key: local-docker-directory 
      - name: Run docker container
        working-directory: ./ 
        run: docker compose -f ./base-compose.yaml -f ./service-1/docker-compose.yaml up


