name: Node.js CI

on:
  push:
    branches: [ feature-1 ]
  pull_request:
    branches: [ feature-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn
        working-directory: ./service-1
      - run: yarn test
        working-directory: ./service-1

      